added init file for debian

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -10,8 +10,9 @@
 #     Guilhem Saurel for Sierra Wireless - initial script
 #*******************************************************************************
 
-mkdir -p /opt/mihini
-cd /opt/mihini
+useradd -b /opt -U mihini
+
+cd ~mihini
 
 for rw in persist update apps
 do
@@ -19,5 +20,82 @@ do
     ln -s /var/opt/mihini/$rw
 done
 
-#useradd -b /opt -U mihini
-#chown -R mihini:mihini /{var/,}opt/mihini
+chown -R mihini:mihini /{var/,}opt/mihini
+
+cat << EOF > /etc/init.d/mihini
+#!/bin/sh
+
+### BEGIN INIT INFO
+# Provides: mihini_agent
+# Required-Start: \$remote_fs \$syslog
+# Required-Stop: \$remote_fs \$syslog
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: Start mihini agent at boot time
+# Description: Enable application framework or M2M services (like device management) provided by mihini agent.
+### END INIT INFO
+
+#log_success_msg, log_failure_msg and log_warning_msg
+
+DESC="Mihini agent"
+NAME=Mihini
+DAEMON=/opt/mihini/bin/appmon_daemon
+AGENT=/opt/mihini/bin/agent
+ROOTDIR=/opt/mihini
+
+. /lib/lsb/init-functions
+
+test -f \$DAEMON || exit 0
+test -f \$AGENT || exit 0
+
+case "\$1" in
+    start)
+        if [ ! "`pidof \$DAEMON`" ]
+        then
+            \$DAEMON -a \$AGENT -w \$ROOTDIR -u mihini -g mihini -n 5 2>&1 | logger -t Mihini &
+            if [ "\$?" -eq 0  ]
+            then
+                log_success_msg "\$NAME started"
+            else
+                log_failure_msg "\$NAME failed to start"
+            fi
+            sleep 1
+        fi
+        ;;
+
+    stop)
+        log_daemon_msg "Stopping \$NAME agent"
+        echo "destroy" | nc localhost 4242 > /dev/null 2>&1
+        killproc \$AGENT
+        log_end_msg \$?
+
+        log_daemon_msg "Stopping \$NAME daemon"
+        killproc \$DAEMON
+        log_end_msg \$?
+        ;;
+
+    restart)
+        \$0 stop
+        \$0 start
+        \$0 status
+        ;;
+
+    status)
+        status_of_proc \$DAEMON "\$NAME daemon"
+        status_of_proc \$AGENT "\$NAME agent"
+        ;;
+
+    purge)
+        log_daemon_msg "Not Yet Implemented…"
+        ;;
+
+    *)
+      echo "Usage: \$0 {start|stop|restart|status|purge}"
+      exit 1
+      ;;
+esac
+
+exit 0
+EOF
+
+chmod +x /etc/init.d/mihini
